spring:
  application:
    name: pagamentos-app
  cloud:
    gcp:
      firestore:
        enabled: true
        project-id: fiap-tech-challenge-403000
        database-id: pagamentos-db
pagamento:
  feign:
    pedido:
      url: https://pedidos-service-jeyzneivqa-rj.a.run.app