spring:
  cloud:
    function:
      definition: confirmarPagamentoSupplier;solicitarPagamentoConsumer;
    stream:
      bindings:
        confirmarPagamentoSupplier-out-0:
          destination: confirmar-pagamento-topic
        solicitarPagamentoConsumer-in-0:
          group: pagamentos-subscription
          destination: solicitar-pagamento-topic
    gcp:
      project-id: fiap-tech-challenge-store
      pubsub:
        emulator-host: localhost:8085
      firestore:
        # para teste local usar versão <spring-cloud-gcp.version>4.7.2</spring-cloud-gcp.version>
        database-id: default
        host-port: localhost:8090
        emulator:
          enabled: true