spring:
  application:
    name: pagamentos-app
  cloud:
    function:
      definition: solicitarPagamentoConsumer;
    stream:
      function:
        bindings:
          confirmarPagamentoSupplier-out-0: confirmarPagamentoSupplier
      bindings:
        confirmarPagamentoSupplier:
          destination: confirmar-pagamento-topic
        solicitarPagamentoConsumer-in-0:
          group: pagamentos-subscription
          destination: solicitar-pagamento-topic
    gcp:
      pubsub:
        subscriber:
          max-ack-extension-period: 60
          min-duration-per-ack-extension: 60
      project-id: fiap-tech-challenge-403000
      firestore:
        enabled: true
        database-id: pagamentos-db
pagamento:
  feign:
    pedido:
      url: https://pedidos-service-jeyzneivqa-rj.a.run.app