apiVersion: v1
kind: Service
metadata:
  name: pagamento-app
  labels:
    app: pagamento-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pagamento-app